### ISSUE TITLE
Integration atagone not found

### ISSUE THREAD

**Issue by RezzZ** [herikw/home-assistant-custom-components#11]
Just updated HA to 0.93. Besides the empty __init__.py file we no also require a manifest.json file. I got the errors:
```
Integration atagone not found when trying to verify its climate platform.
Integration atagone not found when trying to verify its sensor platform.
```

Took the liberty to create one myself:

```
{
  "domain": "atagone",
  "name": "AtagOne custom component",
  "documentation": "https://github.com/herikw/home-assistant-custom-components",
  "requirements": [],
  "dependencies": [],
  "codeowners": ["@herikw"]
}
```

source:
https://developers.home-assistant.io/docs/en/creating_integration_manifest.html

**Comment by RezzZ** [comment]
unfortunately the climate component keeps failing to start on my side. Sensors are working fine:
```
Error while setting up platform atagone
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/atagone/climate.py", line 116, in setup_platform
    add_devices([AtagOneThermostat(config.get(CONF_NAME), config.get(CONF_HOST), config.get(CONF_PORT))])
  File "/config/custom_components/atagone/climate.py", line 138, in __init__
    self.update()
  File "/config/custom_components/atagone/climate.py", line 265, in update
    resp = self.send_request(self, READ_PATH, jsonPayload)
  File "/config/custom_components/atagone/climate.py", line 149, in send_request
    with urllib.request.urlopen(req, timeout=30) as result:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```
anyone else experiencing this?

**Comment by reharmsen** [comment]
@RezzZ For me the component works fine. Al tough I am using a fork of the component due to Google Assistant problems with the original of @herikw 

As for you log... I am seeing a "timed out" error.
Is your Atag One reachable? IS the component setup with the correct IP/Hostname?

**Comment by RezzZ** [comment]
I can reach my atagone with the original app yes, but I do encounter lots of wifi problems with the device. it's almost attached to my accesspoint but still the connection is often reporten as poor/bad. Perhaps I need to request a new atagone..

**Comment by RezzZ** [comment]
hmm I found/remembered an old post on tweakers.net regarding the channel of my WiFi. I switched my relatively new IoT network to to channel 6 and restarted HA. The device is available again. Hope it stays that way.

edit: I do still find lots of update sensor fails in my HA logs though.
```
urllib.error.URLError: <urlopen error [Errno 113] Host is unreachable>
```
And already upped that timeout to 30secs.
